spring:
  application:
    name: UserService
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/mvc?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: root

mybatis-plus:
  type-aliases-package: com.hls.common.entity

server:
  port: 9090

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7000/eureka/